name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Ensure submodules are updated

    - name: Setup Ruby for Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Specify the Ruby version you want to use

    - name: Install dependencies for Jekyll blog
      working-directory: ./blog  # Change directory to blog
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll blog
      working-directory: ./blog  # Change directory to blog
      run: bundle exec jekyll build -d ../build_output/blog

    - name: Copy static HTML site
      run: |
        mkdir -p build_output
        rsync -av --exclude='build_output' --exclude='blog' --exclude='.git' --exclude='.github' . build_output/

    - name: List build_output directory contents for debugging
      run: ls -R build_output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./build_output
